title: MinDoc Template # You will insert your title here.
email: your-email@example.com
description: by Authors # Author names go here.

baseurl: "" # Leave this empty. When empty, MinDoc automatically uses your GitHub repository name as the site's subpath, so you don't need to edit this. Only set a value (e.g. "/your-repo-name") if you need to override that automatic behavior.

twitter_username: jekyllrb
github_username:  jekyll

# Build settings

plugins:
  - jekyll-feed

collections:
  mindoc_media:
    output: true
    layout: 'image_description'
